### ISSUE TITLE
Convert string to byte string on common.py 

### ISSUE THREAD

**Issue by Futabay** [NASA-AMMOS/AIT-DSN#118]
In Python3, there is no implicit conversion between string object and byte object. Thus, for example, string and byte-string concatenation is not working. 

https://github.com/NASA-AMMOS/AIT-DSN/blob/4780d6d5c54a2b7b6ee71285bd08d15e2c937129/ait/dsn/sle/common.py#L446

Following stings need to be converted to byte-string 

https://github.com/NASA-AMMOS/AIT-DSN/blob/4780d6d5c54a2b7b6ee71285bd08d15e2c937129/ait/dsn/sle/common.py#L435

https://github.com/NASA-AMMOS/AIT-DSN/blob/4780d6d5c54a2b7b6ee71285bd08d15e2c937129/ait/dsn/sle/common.py#L454

https://github.com/NASA-AMMOS/AIT-DSN/blob/4780d6d5c54a2b7b6ee71285bd08d15e2c937129/ait/dsn/sle/common.py#L465

**Comment by MJJoyce** [comment]
Resolved in #120
