### ISSUE TITLE
Push DSN build to PyPi

### ISSUE THREAD

**Issue by MJJoyce** [NASA-AMMOS/AIT-DSN#12]
@MJJoyce commented on [Wed Apr 11 2018](https://github.com/NASA-AMMOS/AIT-Core/issues/19)

**Comment by lorsposto** [comment]
Done. 
1.0.0 release: https://github.com/NASA-AMMOS/AIT-DSN/releases/tag/1.0.0
Pypi: https://pypi.org/project/ait-dsn/
