### ISSUE TITLE
Implement AOS Transfer Frames 

### ISSUE THREAD

**Issue by aywaldron** [NASA-AMMOS/AIT-DSN#60]
Small sat missions use AOS transfer frames rather than TM transfer frames.

https://github.com/NASA-AMMOS/AIT-DSN/blob/7fb34ea57284224c36d26a8637ddfb1e6d22e4f7/ait/dsn/sle/frames.py#L83

- Configuration of transfer frame also needs to be defined in sle_tlm.yaml
https://github.com/NASA-AMMOS/AIT-DSN/blob/master/ait/dsn/sle/frames.py
- TMTransFrame referenced in raf.py and rcf.py - these would need to be changed (also in ait_sle_bridge.py example)
- RAF sends `frame._data` to telem socket in `RAF._transfer_data_invoc_handler` - needs to be changed either by sub-classing or explicitly overwriting `self._handlers` for that handler type (`frame._data` is filled in frame class in frames.py)
https://github.com/NASA-AMMOS/AIT-DSN/blob/7fb34ea57284224c36d26a8637ddfb1e6d22e4f7/ait/dsn/sle/raf.py#L328

**Comment by kmarwah** [comment]
Hey, I'm working with the LunaH-Map team and I'm currently working on implementing this. It should be done in a few days or so. Can you please explain the changes required in `RAF._transfer_data_invoc_handler` in greater detail? Thanks!

**Comment by aywaldron** [comment]
Hi @kmarwah, that's great to hear! So the last two bullet points above are referring to the same thing, the last one is just providing detail. The code in RAF here
https://github.com/NASA-AMMOS/AIT-DSN/blob/9e1e0c4cf283d340d95152ccc46010d6b6639673/ait/dsn/sle/raf.py#L337 and in RCF here https://github.com/NASA-AMMOS/AIT-DSN/blob/7fb34ea57284224c36d26a8637ddfb1e6d22e4f7/ait/dsn/sle/rcf.py#L404 uses the `TMTransFrame`. If you will be using RAF or RCF with the `AOSTransFrame` instead, then you will need a way to change the frame that handler uses, or write a new handler. It may make the most sense to add a parameter to the RAF/RCF classes for the type of transfer frame to use, which defaults to `TMTransFrame`, and which the handler then references (@MJJoyce any thoughts on that?)

**Comment by aywaldron** [comment]
@kmarwah implemented AOS transfer frames using the Iris radio's ICD (see PR #69 for details). This implementation should be expanded to match the CCSDS's AOS spec, https://public.ccsds.org/Pubs/732x0b3e1.pdf
