### ISSUE TITLE
Investigate ASU PDU decoding issue

### ISSUE THREAD

**Issue by aywaldron** [NASA-AMMOS/AIT-DSN#79]
ASU received this error
https://github.com/NASA-AMMOS/AIT-DSN/blob/dbd8c163fb49a1440fd4f765cd22c39229e6ec6c/ait/dsn/sle/common.py#L485
when downlinking with RAF during their end-to-end testing.

**Comment by aywaldron** [comment]
We tested using with the simulator available at http://atb-ocio-sspsim.jpl.nasa.gov:7070/ssp and an example PDU from ASU but were not able to duplicate the error. We are waiting ASU to receive a stream of PDUs during their next test for further investigation.

**Comment by MJJoyce** [comment]
After a few chats with their team throughout some testing this seems to be an issue with custom modifications made to the decoding process / tools. They've since done connectivity tests without issue. Nothing to fix here.
