### ISSUE TITLE
Add SLE parameters to config file

### ISSUE THREAD

**Issue by aywaldron** [NASA-AMMOS/AIT-DSN#84]
The following SLE parameters are not currently pulled from the config file:
- RCF:
    - `spacecraft_id` (default 250)
    - `trans_frame_ver_num` (default 0)
- all protocols:
    - `version` (default 4)
    - `auth_level`

This ticket should be addressed after configuration formatting changes introduced by #64 are merged in.

**Comment by aywaldron** [comment]
Note: these would be added to the config.yaml on a per-protocol basis (i.e. within `dsn.sle.raf`, `dsn.sle.rcf`, `dsn.sle.fcltu`)

**Comment by MJJoyce** [comment]
It looks like this got merged in #85. Closing this out.
