### ISSUE TITLE
Add BCH support to the repo

### ISSUE THREAD

**Issue by nttoole** [NASA-AMMOS/AIT-DSN#92]
Integrate existing support for BCH (Bose, Chaudhuri, Hocquenghem) - provided by Kabir Marwah (ASU) -  into the DSN repository.

**Comment by MJJoyce** [comment]
Note, for tracking purposes and to ensure adequate credit is given, this was contributed by ASU (with minor modifications) through email and phone conversations. At the minimum, I'm aware of @kmarwah and Tyler O'Brien being two of the original developers of the code.

@kmarwah, if the above is incorrect let me know! Similarly, if you know Tyler's Github username put it in here as well!
